AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  DeploymentArtifactsBucket:
    Type: AWS::S3::Bucket

Outputs:
  Bucket:
    Value: !Ref DeploymentArtifactsBucket